### ISSUE TITLE
`Find: In...` not working in ST3 

### ISSUE THREAD

**Issue by thecotne** [twolfson/FindPlusPlus#12]
after trying to use that ST not responding

**Comment by zanuka** [comment]
Find: In... works fine for me in ST3.

**Comment by twolfson** [comment]
@thecotne It's been a year since this was initially reported. Is the issue still occurring?

**Comment by thecotne** [comment]
@twolfson i tested and yes issue is still occurring

i have project with some node_modules installed so node_modules has very big directory tree
when i first launch `Find: In...` it responds with very small lag but when i start searching for something 
that is very common like `node` it's very laggy 
if i search for something that will have small mount of results it's not laggy

btw i switched from windows to linux 
i am testing it with ubuntu 14

**Comment by twolfson** [comment]
Can you elaborate on "searching for something"? Is this after you have selected a folder or when you are filtering the list of folders?

**Comment by thecotne** [comment]
when i am filtering the list of folders

**Comment by twolfson** [comment]
Ah, k. Do you think adding some kind of support for adding an ignore pattern would work for you (e.g. a configuration setting to ignore `node_modules/`)?

**Comment by thecotne** [comment]
if i ignore directory from sublime project settings is it ignored by find++ ?

in rare cases i may want to search in node_modules directory (when go to definition not works or when i want to see how some function is used internally in package)

**Comment by twolfson** [comment]
Yea, if it's ignored by the project, then Find++ should ignore it as well. However, if you need to search `node_modules`, then I can't help you.

There was a possibility to limit by max depth (e.g. only go down by 5 directories) but in `npm@3`, they are moving to a flat folder structure which does us no good.

I am going to leave this issue as open (and open to suggestions) but I don't think there is any fix for your use case other than ignoring folders.
