### ISSUE TITLE
show <binary> error

### ISSUE THREAD

**Issue by wangwang4git** [twolfson/FindPlusPlus#15]
Searching 1 file for "NewFriendManager"

E:\Project\bug fix\bug50532947\XXXX.15.05.01.10.log:
    <binary>

512 matches in 1 file

**Comment by twolfson** [comment]
I don't understand this issue. Can you list out the steps you took, expected behavior, and actual behavior? Screenshots would also be useful.

**Comment by twolfson** [comment]
This issue has fallen silent with no clarification from @wangwang4git. Closing this issue for now.
